### ISSUE TITLE
typo and missing link on payloadsexplorer

### ISSUE THREAD

**Issue by sakulstra** [bgd-labs/aave-governance-v3-interface#58]
![image](https://github.com/bgd-labs/aave-governance-v3-interface/assets/4396533/4c249a28-5707-439a-b188-0c4d0644ba45)

On the "executed at" there seems to be a typo (two commas), also would be quite useful if this date was a link to the execution transaction.

**Comment by Argeare5** [comment]
I'll fix the typo

Regarding the link, this is an interesting point, it is not missing, we simply do not have data about events in payloads in the UI, since we do not need them
You can always open the seatbelt report and from there, if you need to follow the link, if there is no report, then there is no cache for this, which means there will be no link

But adding getting an event and getting a hash for a transaction from it, in my opinion, it doesn’t make sense to do this to implement such a small thing

what do you think @eboadom @kyzia551 ?

**Comment by Argeare5** [comment]
also @sakulstra , I completely forgot, you can use the view inside the rocket

<img width="1086" alt="Снимок экрана 2024-01-24 в 13 48 39" src="https://github.com/bgd-labs/aave-governance-v3-interface/assets/25132555/e2da22b8-e9ac-466d-9191-de065a4b8b78">
<img width="1244" alt="Снимок экрана 2024-01-24 в 13 50 09" src="https://github.com/bgd-labs/aave-governance-v3-interface/assets/25132555/8a73d8d3-02cf-4611-aa9a-81401708305b">

**Comment by sakulstra** [comment]
but you have the event in the cache already 🤔 

It's not the most important feature yes, and i eventually ended up checking on seatbelt.
To me just feels natural though to provide the link so i don't have to click around on different sources to find the txn 🤷

**Comment by Argeare5** [comment]
it is here only upon request, at the moment there are no cached events in the UI

we still can’t merge the refactored caching system...
