### ISSUE TITLE
Error on link to Snapshot on proposal details

### ISSUE THREAD

**Issue by eboadom** [bgd-labs/aave-governance-v3-interface#63]
The link here for Snapshot is wrong, as it is using the IPFS hash of the proposal instead of the Snapshot link

<img width="389" alt="snapshot link" src="https://github.com/bgd-labs/aave-governance-v3-interface/assets/22181752/2d08d243-978c-4f65-9543-af5fc1aa283d">

Example:

On https://vote.onaave.com/proposal/?proposalId=11, the link of "Snapshot voting" is https://snapshot.org/#/aave.eth/proposal/0x2fa324a635a80a4f64b8636199440b6ef8687135aa81ccf396570eb8aecc7bed (non-existent Snapshot link) where is actually the IPFS hash of the proposal https://vote.onaave.com/proposal/?proposalId=11&ipfsHash=0x2fa324a635a80a4f64b8636199440b6ef8687135aa81ccf396570eb8aecc7bed

The correct Snapshot link being https://snapshot.org/#/aave.eth/proposal/0xb8790aeb32267062c1500deb613ad15ebd5deac4d78d1786cb1690c12d0512c9

**Comment by Argeare5** [comment]
We did a little research with @kyzia551 , and it turned out that at the moment there is not enough data from ipfs to generate the correct link to the snapshot, we do not have a link to the snapshot inside `json` of the data that we receive from IPFS.

For now I'll just remove this link.

It would be nice to add a link to a snapshot of the vote in IPFS when creating a proposal, is it possible to do this @sakulstra?

**Comment by sakulstra** [comment]
we could add it as optional(as not all proposals have one) to the ipfs metadata on the proposal generator.

**Comment by Argeare5** [comment]
> we could add it as optional(as not all proposals have one) to the ipfs metadata on the proposal generator.

cool, could you do that?

**Comment by sakulstra** [comment]
sure, for future proposals the optional property might be on the metadata.
